spring.application.name=backend-api
spring.datasource.url=jdbc:postgresql://localhost:5432/sportsdb
spring.datasource.username=sportsuser
spring.datasource.password=sportspass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true